<a href="https://colab.research.google.com/github/ArunimaSaji/numpy/blob/main/pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [136]:
import pandas as pd
import numpy as np

In [137]:
df=pd.read_csv('/content/sample.txt',sep='\t',header=None)
df.columns=['id','name','l_name','age','number','location']
df

    id     name  l_name  age      number   location
0  101    Arjun    Nair   25  9876543210      Kochi
1  102    Meera  Thomas   28  9845012345  Bengaluru
2  103    Rahul  Sharma   30  9123456789      Delhi
3  104    Priya   Menon   22  9745612390   Thrissur
4  105  Karthik    Iyer   27  9988776655    Chennai

In [138]:
df=df.drop(columns=['number','location'])
df

    id     name  l_name  age
0  101    Arjun    Nair   25
1  102    Meera  Thomas   28
2  103    Rahul  Sharma   30
3  104    Priya   Menon   22
4  105  Karthik    Iyer   27

In [139]:
df=df[['id','name','age']]
df

    id     name  age
0  101    Arjun   25
1  102    Meera   28
2  103    Rahul   30
3  104    Priya   22
4  105  Karthik   27

In [140]:
df[['id','name']].head(3)

    id   name
0  101  Arjun
1  102  Meera
2  103  Rahul

In [141]:
df

    id     name  age
0  101    Arjun   25
1  102    Meera   28
2  103    Rahul   30
3  104    Priya   22
4  105  Karthik   27

In [142]:
# loc
# new_df=old_df.loc[old_df[col_name]condition]
df1=df.loc[df['age']>=28]
print(df1)

    id   name  age
1  102  Meera   28
2  103  Rahul   30

In [143]:
df=pd.read_csv('/content/customer1 (1).txt')
df.columns=['id','name','l_name','age','prof','loc']
print(df)

          id      name   l_name  age                        prof        loc
0    4000002     Paige     Chen   74                     Teacher         uk
1    4000003    Sherri   Melton   34                 Firefighter         us
2    4000004  Gretchen     Hill   66  Computer hardware engineer      china
3    4000005     Karen  Puckett   74                      Lawyer     africa
4    4000006   Patrick     Song   42                Veterinarian  australia
..       ...       ...      ...  ...                         ...        ...
457  4000459  Gretchen  Francis   60                  Politician    ireland
458  4000460    Cheryl     Horn   40                Veterinarian    ireland
459  4000461    Audrey  Forrest   50                   Architect    ireland
460  4000462      Alan    Levin   43                Statistician    ireland
461  4000463     Wayne   Weiner   70                       Actor    ireland

[462 rows x 6 columns]

In [144]:
df1=df.loc[df['age']>50][['name','l_name','age']]
print(df1)

         name      l_name  age
0       Paige        Chen   74
2    Gretchen        Hill   66
3       Karen     Puckett   74
6       Hazel      Bender   63
8     Dolores  McLaughlin   60
..        ...         ...  ...
445    Jordan      Knight   65
451       Kim     Hensley   64
453   Deborah      French   56
457  Gretchen     Francis   60
461     Wayne      Weiner   70

[234 rows x 3 columns]

In [145]:
df3=df.loc[df['prof']=='Pilot']
df3

          id       name    l_name  age   prof        loc
5    4000007      Elsie  Hamilton   43  Pilot    ireland
227  4000229       Faye    Norman   64  Pilot     africa
228  4000230      Kathy     Burch   28  Pilot     africa
249  4000251     Jeremy     House   61  Pilot     africa
269  4000271      Alice     Nance   59  Pilot     africa
320  4000322  Geraldine    Jensen   50  Pilot  australia
334  4000336     Steven   Ballard   62  Pilot  australia
390  4000392       Emma     Olson   74  Pilot    ireland
401  4000403        Leo  Lassiter   65  Pilot    ireland
421  4000423       Alan    O'Neal   59  Pilot    ireland
423  4000425       Dean      Lutz   26  Pilot    ireland
438  4000440     Hannah  Langston   25  Pilot    ireland

In [146]:
df4=df.loc[(df['age']>50) & (df['prof']=='Pilot')]
df4

          id    name    l_name  age   prof        loc
227  4000229    Faye    Norman   64  Pilot     africa
249  4000251  Jeremy     House   61  Pilot     africa
269  4000271   Alice     Nance   59  Pilot     africa
334  4000336  Steven   Ballard   62  Pilot  australia
390  4000392    Emma     Olson   74  Pilot    ireland
401  4000403     Leo  Lassiter   65  Pilot    ireland
421  4000423    Alan    O'Neal   59  Pilot    ireland

In [147]:
df.shape

(462, 6)

In [148]:
df.size

2772

In [149]:
df.dtypes

id         int64
name      object
l_name    object
age        int64
prof      object
loc       object
dtype: object

In [150]:
df.describe(include='all')

                  id    name  l_name         age              prof        loc
count   4.620000e+02     462     462  462.000000               462        461
unique           NaN     307     365         NaN                51          7
top              NaN  Glenda  Weiner         NaN  Childcare worker  australia
freq             NaN       5       3         NaN                17        104
mean    4.000232e+06     NaN     NaN   49.662338               NaN        NaN
std     1.335122e+02     NaN     NaN   15.621841               NaN        NaN
min     4.000002e+06     NaN     NaN   21.000000               NaN        NaN
25%     4.000117e+06     NaN     NaN   36.000000               NaN        NaN
50%     4.000232e+06     NaN     NaN   51.000000               NaN        NaN
75%     4.000348e+06     NaN     NaN   64.000000               NaN        NaN
max     4.000463e+06     NaN     NaN   75.000000               NaN        NaN

In [151]:
df.isna()

        id   name  l_name    age   prof    loc
0    False  False   False  False  False  False
1    False  False   False  False  False  False
2    False  False   False  False  False  False
3    False  False   False  False  False  False
4    False  False   False  False  False  False
..     ...    ...     ...    ...    ...    ...
457  False  False   False  False  False  False
458  False  False   False  False  False  False
459  False  False   False  False  False  False
460  False  False   False  False  False  False
461  False  False   False  False  False  False

[462 rows x 6 columns]

In [152]:
df.isna().sum()

id        0
name      0
l_name    0
age       0
prof      0
loc       1
dtype: int64

In [153]:
df

          id      name   l_name  age                        prof        loc
0    4000002     Paige     Chen   74                     Teacher         uk
1    4000003    Sherri   Melton   34                 Firefighter         us
2    4000004  Gretchen     Hill   66  Computer hardware engineer      china
3    4000005     Karen  Puckett   74                      Lawyer     africa
4    4000006   Patrick     Song   42                Veterinarian  australia
..       ...       ...      ...  ...                         ...        ...
457  4000459  Gretchen  Francis   60                  Politician    ireland
458  4000460    Cheryl     Horn   40                Veterinarian    ireland
459  4000461    Audrey  Forrest   50                   Architect    ireland
460  4000462      Alan    Levin   43                Statistician    ireland
461  4000463     Wayne   Weiner   70                       Actor    ireland

[462 rows x 6 columns]

In [154]:
print(df.shape)
print(df.size)
print(df.tail()
)
print(df.head())
print(len(df))
print(df.dtypes)
print(df.describe(include='all'))

(462, 6)
2772
          id      name   l_name  age          prof      loc
457  4000459  Gretchen  Francis   60    Politician  ireland
458  4000460    Cheryl     Horn   40  Veterinarian  ireland
459  4000461    Audrey  Forrest   50     Architect  ireland
460  4000462      Alan    Levin   43  Statistician  ireland
461  4000463     Wayne   Weiner   70         Actor  ireland
        id      name   l_name  age                        prof        loc
0  4000002     Paige     Chen   74                     Teacher         uk
1  4000003    Sherri   Melton   34                 Firefighter         us
2  4000004  Gretchen     Hill   66  Computer hardware engineer      china
3  4000005     Karen  Puckett   74                      Lawyer     africa
4  4000006   Patrick     Song   42                Veterinarian  australia
462
id         int64
name      object
l_name    object
age        int64
prof      object
loc       object
dtype: object
                  id    name  l_name         age              prof        loc
count   4.620000e+02     462     462  462.000000               462        461
unique           NaN     307     365         NaN                51          7
top              NaN  Glenda  Weiner         NaN  Childcare worker  australia
freq             NaN       5       3         NaN                17        104
mean    4.000232e+06     NaN     NaN   49.662338               NaN        NaN
std     1.335122e+02     NaN     NaN   15.621841               NaN        NaN
min     4.000002e+06     NaN     NaN   21.000000               NaN        NaN
25%     4.000117e+06     NaN     NaN   36.000000               NaN        NaN
50%     4.000232e+06     NaN     NaN   51.000000               NaN        NaN
75%     4.000348e+06     NaN     NaN   64.000000               NaN        NaN
max     4.000463e+06     NaN     NaN   75.000000               NaN        NaN

In [155]:
df.isna().sum()

id        0
name      0
l_name    0
age       0
prof      0
loc       1
dtype: int64

In [156]:
# df.fillna('australia',inplace=True)
df.dropna(inplace=True)
print(df.isna().sum())
df.shape

id        0
name      0
l_name    0
age       0
prof      0
loc       0
dtype: int64

(461, 6)

In [157]:
df.duplicated().sum()

np.int64(0)

In [158]:
df1=df.iloc[:,1:]
df1

         name   l_name  age                        prof        loc
0       Paige     Chen   74                     Teacher         uk
1      Sherri   Melton   34                 Firefighter         us
2    Gretchen     Hill   66  Computer hardware engineer      china
3       Karen  Puckett   74                      Lawyer     africa
4     Patrick     Song   42                Veterinarian  australia
..        ...      ...  ...                         ...        ...
457  Gretchen  Francis   60                  Politician    ireland
458    Cheryl     Horn   40                Veterinarian    ireland
459    Audrey  Forrest   50                   Architect    ireland
460      Alan    Levin   43                Statistician    ireland
461     Wayne   Weiner   70                       Actor    ireland

[461 rows x 5 columns]

In [159]:
df1=df.loc[df['prof']=='Teacher'].sort_values(by='age')
df1

          id     name   l_name  age     prof        loc
395  4000397     Bill    Klein   26  Teacher    ireland
61   4000063  Melinda  Proctor   27  Teacher         uk
99   4000101    Scott   Golden   27  Teacher         us
373  4000375   Norman      Lam   63  Teacher  australia
0    4000002    Paige     Chen   74  Teacher         uk

In [160]:
df1=df.loc[df['prof']=='Teacher'].sort_values(by='age',ascending=False).head(4)
df1

          id     name   l_name  age     prof        loc
0    4000002    Paige     Chen   74  Teacher         uk
373  4000375   Norman      Lam   63  Teacher  australia
61   4000063  Melinda  Proctor   27  Teacher         uk
99   4000101    Scott   Golden   27  Teacher         us

In [161]:
p_c=df.groupby('prof')['prof'].count().sort_values(ascending=False)
print(p_c)

prof
Childcare worker                   17
Musician                           15
Photographer                       15
Loan officer                       14
Veterinarian                       13
Doctor                             13
Computer support specialist        12
Actor                              12
Pilot                              12
Civil engineer                     11
Statistician                       11
Electrical engineer                11
Politician                         11
Carpenter                          10
Economist                          10
Social worker                      10
Human resources assistant          10
Lawyer                             10
Environmental scientist            10
Agricultural and food scientist     9
Coach                               9
Accountant                          9
Recreation and fitness worker       9
Firefighter                         9
Designer                            9
Dancer                              9
Athlete                             9
Engineering technician              9
Nurse                               9
Therapist                           8
Artist                              8
Architect                           8
Reporter                            8
Pharmacist                          8
Secretary                           8
Electrician                         8
Librarian                           8
Physicist                           8
Farmer                              8
Police officer                      7
Computer hardware engineer          7
Computer software engineer          7
Automotive mechanic                 6
Chemist                             6
Real estate agent                   6
Judge                               6
Teacher                             5
Psychologist                        5
Writer                              5
Financial analyst                   4
Name: prof, dtype: int64

In [162]:
df1=df.loc[df['loc']=='india'].groupby('prof')['prof'].count().sort_values()
df1

prof
Accountant                     1
Artist                         1
Childcare worker               1
Computer support specialist    1
Doctor                         1
Dancer                         1
Engineering technician         1
Environmental scientist        1
Therapist                      1
Financial analyst              1
Lawyer                         1
Pharmacist                     1
Writer                         2
Carpenter                      3
Musician                       3
Name: prof, dtype: int64

In [163]:
df1=df.loc[df['loc']=='india'].groupby('age')['age'].max()
df1

age
26    26
27    27
28    28
39    39
41    41
42    42
45    45
47    47
49    49
52    52
60    60
63    63
64    64
65    65
66    66
67    67
72    72
Name: age, dtype: int64

In [164]:
df1=df.groupby('prof')['age'].mean()
df1

prof
Accountant                         54.888889
Actor                              58.000000
Agricultural and food scientist    46.222222
Architect                          44.500000
Artist                             50.500000
Athlete                            51.222222
Automotive mechanic                47.000000
Carpenter                          49.700000
Chemist                            51.833333
Childcare worker                   51.411765
Civil engineer                     55.727273
Coach                              41.888889
Computer hardware engineer         52.857143
Computer software engineer         58.142857
Computer support specialist        47.166667
Dancer                             50.555556
Designer                           50.000000
Doctor                             51.538462
Economist                          47.100000
Electrical engineer                50.363636
Electrician                        49.000000
Engineering technician             51.555556
Environmental scientist            48.500000
Farmer                             52.125000
Financial analyst                  53.500000
Firefighter                        46.888889
Human resources assistant          45.800000
Judge                              48.000000
Lawyer                             44.800000
Librarian                          44.000000
Loan officer                       49.214286
Musician                           49.800000
Nurse                              49.666667
Pharmacist                         51.250000
Photographer                       55.400000
Physicist                          43.750000
Pilot                              51.333333
Police officer                     46.714286
Politician                         48.363636
Psychologist                       50.200000
Real estate agent                  44.500000
Recreation and fitness worker      44.888889
Reporter                           45.375000
Secretary                          50.125000
Social worker                      55.900000
Statistician                       50.090909
Teacher                            43.400000
Therapist                          52.500000
Veterinarian                       47.461538
Writer                             44.600000
Name: age, dtype: float64

In [165]:
df

          id      name   l_name  age                        prof        loc
0    4000002     Paige     Chen   74                     Teacher         uk
1    4000003    Sherri   Melton   34                 Firefighter         us
2    4000004  Gretchen     Hill   66  Computer hardware engineer      china
3    4000005     Karen  Puckett   74                      Lawyer     africa
4    4000006   Patrick     Song   42                Veterinarian  australia
..       ...       ...      ...  ...                         ...        ...
457  4000459  Gretchen  Francis   60                  Politician    ireland
458  4000460    Cheryl     Horn   40                Veterinarian    ireland
459  4000461    Audrey  Forrest   50                   Architect    ireland
460  4000462      Alan    Levin   43                Statistician    ireland
461  4000463     Wayne   Weiner   70                       Actor    ireland

[461 rows x 6 columns]

In [166]:
df1=df.groupby('prof')['prof'].count().sort_values(ascending=False)
print(df1)

prof
Childcare worker                   17
Musician                           15
Photographer                       15
Loan officer                       14
Veterinarian                       13
Doctor                             13
Computer support specialist        12
Actor                              12
Pilot                              12
Civil engineer                     11
Statistician                       11
Electrical engineer                11
Politician                         11
Carpenter                          10
Economist                          10
Social worker                      10
Human resources assistant          10
Lawyer                             10
Environmental scientist            10
Agricultural and food scientist     9
Coach                               9
Accountant                          9
Recreation and fitness worker       9
Firefighter                         9
Designer                            9
Dancer                              9
Athlete                             9
Engineering technician              9
Nurse                               9
Therapist                           8
Artist                              8
Architect                           8
Reporter                            8
Pharmacist                          8
Secretary                           8
Electrician                         8
Librarian                           8
Physicist                           8
Farmer                              8
Police officer                      7
Computer hardware engineer          7
Computer software engineer          7
Automotive mechanic                 6
Chemist                             6
Real estate agent                   6
Judge                               6
Teacher                             5
Psychologist                        5
Writer                              5
Financial analyst                   4
Name: prof, dtype: int64